import React, { useState, useRef, useEffect, useCallback } from 'react';
import { useGame } from '../context/GameContext';
import { getCleanName } from '../utils/pokemon';
import pokemonNamesJson from '../data/pokemon_names.json';
import { CreditsModal } from './CreditsModal';

// Language codes match the PokeAPI `language.name` field returned by the pokemon-species endpoint.
// The JSON is generated by scripts/generate_pokemon_names.py and has the shape:
//   { "pokemonId": { "languageCode": "name", ... } }
//
// English flag uses 🇬🇧 (UK) per best-practice guidance at flagsarenotlanguages.com.
const POKEMON_LANGUAGES = [
    { code: 'global',  label: 'Global',    flag: '🌐', langCode: null      },
    { code: 'en',      label: 'English',   flag: '🇬🇧', langCode: 'en'     },
    { code: 'fr',      label: 'Français',  flag: '🇫🇷', langCode: 'fr'     },
    { code: 'de',      label: 'Deutsch',   flag: '🇩🇪', langCode: 'de'     },
    { code: 'es',      label: 'Español',   flag: '🇪🇸', langCode: 'es'     },
    { code: 'it',      label: 'Italiano',  flag: '🇮🇹', langCode: 'it'     },
    { code: 'ja',      label: '日本語',     flag: '🇯🇵', langCode: 'ja'     },
    { code: 'roomaji', label: 'ローマ字',   flag: '🇯🇵', langCode: 'ja-Hrkt'},
    { code: 'ko',      label: '한국어',     flag: '🇰🇷', langCode: 'ko'     },
    { code: 'zh-Hant', label: '繁體中文',   flag: '🇹🇼', langCode: 'zh-Hant'},
    { code: 'zh-Hans', label: '简体中文',   flag: '🇨🇳', langCode: 'zh-Hans'},
] as const;
type LanguageCode = typeof POKEMON_LANGUAGES[number]['code'];

// The pokemon_names.json can be either the new keyed format { langCode: name }
// or the legacy positional array format. We normalise to the keyed format at runtime.
const LEGACY_LANG_ORDER = ['ja', 'ja-Hrkt', 'ko', 'zh-Hant', 'fr', 'de', 'en', 'zh-Hans'];

type NamesMap = Record<string, Record<string, string>>;

function normalisePokemonNames(raw: Record<string, unknown>): NamesMap {
    const result: NamesMap = {};
    for (const [id, val] of Object.entries(raw)) {
        if (Array.isArray(val)) {
            // Legacy format: positional array → convert to keyed object
            const keyed: Record<string, string> = {};
            (val as string[]).forEach((name, i) => {
                if (name && LEGACY_LANG_ORDER[i]) keyed[LEGACY_LANG_ORDER[i]] = name;
            });
            result[id] = keyed;
        } else if (val && typeof val === 'object') {
            result[id] = val as Record<string, string>;
        }
    }
    return result;
}

const pokemonNames: NamesMap = normalisePokemonNames(pokemonNamesJson as Record<string, unknown>);

export const GlobalGuessInput: React.FC = () => {
    const { allPokemon, checkedIds, checkPokemon, gameMode, isPokemonGuessable, activePokemonLimit, releasedIds, recatchPokemon, toast, showToast, STARTER_OFFSET, MILESTONE_OFFSET, goalCount, startGame, startingLocationsEnabled, gameStarted } = useGame();
    const [guess, setGuess] = useState('');
    const inputRef = useRef<HTMLInputElement>(null);
    const [isCreditsOpen, setIsCreditsOpen] = useState(false);

    // Language selector state
    const [selectedLanguage, setSelectedLanguage] = useState<LanguageCode>(() =>
        (localStorage.getItem('pokepelago_language') as LanguageCode) ?? 'global'
    );
    const [langMenuOpen, setLangMenuOpen] = useState(false);

    // Close language menu when clicking outside
    useEffect(() => {
        if (!langMenuOpen) return;
        const close = () => setLangMenuOpen(false);
        document.addEventListener('mousedown', close);
        return () => document.removeEventListener('mousedown', close);
    }, [langMenuOpen]);

    const handleSelectLanguage = (code: LanguageCode) => {
        setSelectedLanguage(code);
        localStorage.setItem('pokepelago_language', code);
        setLangMenuOpen(false);
    };

    // Debug trigger (dev/beta only)
    useEffect(() => {
        if (!import.meta.env.DEV && !__IS_BETA__) return;
        if (guess.toLowerCase().trim() === 'myuncleworksatnintendo') {
            if ((window as any).toggleDebug) {
                (window as any).toggleDebug();
                setGuess('');
            }
        }
    }, [guess]);

    const checkedIdsRef = useRef(checkedIds);
    const isPokemonGuessableRef = useRef(isPokemonGuessable);
    const releasedIdsRef = useRef(releasedIds);

    useEffect(() => {
        checkedIdsRef.current = checkedIds;
        isPokemonGuessableRef.current = isPokemonGuessable;
        releasedIdsRef.current = releasedIds;
    }, [checkedIds, isPokemonGuessable, releasedIds]);

    // Expose auto-complete for debug (dev/beta only)
    useEffect(() => {
        if (!import.meta.env.DEV && !__IS_BETA__) return;
        (window as any).runAutoComplete = async () => {
            (window as any).isAutoCompleting = true;
            console.log("Starting Auto-Complete Simulation...");

            while ((window as any).isAutoCompleting) {
                let guessedThisLoop = false;
                for (const p of allPokemon) {
                    if (!(window as any).isAutoCompleting) break;

                    const id = p.id;
                    if (checkedIdsRef.current.has(id) && !releasedIdsRef.current.has(id)) continue;

                    const guessCheck = isPokemonGuessableRef.current(id);
                    if (!guessCheck.canGuess) continue;

                    guessedThisLoop = true;
                    setGuess(p.name);
                    await new Promise(r => setTimeout(r, 80));
                }

                if (!guessedThisLoop) {
                    await new Promise(r => setTimeout(r, 200));
                }
            }

            setGuess('');
            (window as any).isAutoCompleting = false;
        };

        (window as any).stopAutoComplete = () => {
            (window as any).isAutoCompleting = false;
        };
    }, [allPokemon]);

    // Shared name-matching helper — returns true if `normalised` matches any accepted name for `p`
    // under the current selectedLanguage.
    const matchesPokemon = useCallback((p: typeof allPokemon[0], normalised: string): boolean => {
        const strip = (s: string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/g, '');
        const sn = strip(normalised);

        const strMatches = (s: string): boolean => {
            const sl = s.toLowerCase();
            const sc = getCleanName(s).toLowerCase();
            return sl === normalised || sc === normalised ||
                (sn !== '' && (strip(sl) === sn || strip(sc) === sn));
        };

        // Always check the primary English name (p.name) from metadata
        const raw = p.name.toLowerCase();
        const clean = getCleanName(p.name).toLowerCase();
        const englishMatch = raw === normalised || clean === normalised ||
            (sn !== '' && (strip(raw) === sn || strip(clean) === sn));

        const langNames: Record<string, string> = pokemonNames[p.id.toString()] ?? {};

        // Also check the English species name from pokemon_names.json — this handles form-named
        // metadata entries like "basculin-red-striped" or "meowstic-male" where the player
        // should be able to type the plain species name ("Basculin", "Meowstic").
        const enSpeciesMatch = langNames['en'] ? strMatches(langNames['en']) : false;

        if (selectedLanguage === 'en') return englishMatch || enSpeciesMatch;

        if (selectedLanguage === 'global') {
            if (englishMatch || enSpeciesMatch) return true;
            return Object.values(langNames).some(name => strMatches(name));
        }

        // Specific non-English language: only check the one localised name
        const langDef = POKEMON_LANGUAGES.find(l => l.code === selectedLanguage);
        if (!langDef || langDef.langCode === null) return false;
        const locName = langNames[langDef.langCode];
        return locName ? strMatches(locName) : false;
    }, [selectedLanguage, allPokemon]);

    // Resolve display name in the selected language (falls back to English clean name).
    const displayName = useCallback((p: typeof allPokemon[0]): string => {
        const names = pokemonNames[p.id.toString()];
        const local = selectedLanguage !== 'global' && names?.[selectedLanguage];
        return local || getCleanName(p.name);
    }, [selectedLanguage, allPokemon]);

    // Auto-submit logic
    useEffect(() => {
        const normalised = guess.toLowerCase().trim();
        if (normalised.length < 3) return;

        const match = allPokemon.find(p => {
            if (!matchesPokemon(p, normalised)) return false;
            if (checkedIds.has(p.id) && !releasedIds.has(p.id)) return false;
            return isPokemonGuessable(p.id).canGuess || releasedIds.has(p.id);
        });

        if (match) {
            if (releasedIds.has(match.id)) {
                recatchPokemon(match.id);
                showToast('recaught', `Re-caught ${displayName(match)}!`);
            } else {
                if (startingLocationsEnabled && !gameStarted && gameMode === 'archipelago') startGame();
                checkPokemon(match.id);
                showToast('success', `✓ ${displayName(match)}!`);
            }
            setGuess('');
        }
    }, [guess, allPokemon, checkedIds, checkPokemon, isPokemonGuessable, releasedIds, recatchPokemon, matchesPokemon]);

    const attemptGuess = (name: string) => {
        const normalised = name.toLowerCase().trim();
        const match = allPokemon.find(p => matchesPokemon(p, normalised));

        if (!match) {
            showToast('error', `✗ ${normalised}`);
            return;
        }

        if (releasedIds.has(match.id)) {
            recatchPokemon(match.id);
            showToast('recaught', `Re-caught ${displayName(match)}!`);
            setGuess('');
            return;
        }

        if (checkedIds.has(match.id)) {
            showToast('already', `Already guessed ${displayName(match)}`);
            setGuess('');
            return;
        }

        const guessCheck = isPokemonGuessable(match.id);
        if (!guessCheck.canGuess) {
            const reason = gameMode === 'standalone' ? 'Generation Locked' : (guessCheck.reason || 'Not found or not unlocked');
            showToast('error', `✗ ${reason}`);
            return;
        }

        if (startingLocationsEnabled && !gameStarted && gameMode === 'archipelago') startGame();
        checkPokemon(match.id);
        showToast('success', `✓ ${displayName(match)}!`);
        setGuess('');
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (!guess.trim()) return;
        attemptGuess(guess);
    };

    const currentLang = POKEMON_LANGUAGES.find(l => l.code === selectedLanguage) ?? POKEMON_LANGUAGES[0];

    return (
        <>
        <div className="relative z-30 bg-gray-950 border-b border-gray-800 shrink-0">
            <div className="max-w-7xl mx-auto flex items-center gap-3 px-4 py-3">
                {/* Logo */}
                <h1
                    className="text-xl font-black tracking-tight bg-linear-to-r from-green-400 to-emerald-500 bg-clip-text text-transparent whitespace-nowrap hidden sm:block cursor-pointer hover:opacity-75 transition-opacity select-none"
                    onClick={() => setIsCreditsOpen(true)}
                    title="Credits & Changelog"
                >
                    Poképelago
                </h1>

                {/* Input */}
                <form onSubmit={handleSubmit} className="flex-1 relative max-w-md">
                    <div className="flex items-center gap-2">
                        <span className="text-gray-400 text-sm whitespace-nowrap">Name a Pokémon:</span>
                        <input
                            ref={inputRef}
                            type="text"
                            value={guess}
                            onChange={(e) => setGuess(e.target.value)}
                            placeholder=""
                            className="flex-1 px-3 py-1.5 bg-gray-800 border border-gray-600 rounded text-white text-sm outline-none focus:border-green-500 transition-colors"
                            autoComplete="off"
                            spellCheck={false}
                        />
                    </div>
                </form>

                {/* Language Selector */}
                <div className="relative">
                    <button
                        type="button"
                        onClick={() => setLangMenuOpen(prev => !prev)}
                        title="Guess language"
                        className="flex items-center gap-1 px-2 py-1.5 bg-gray-800 border border-gray-600 rounded text-sm hover:border-green-500 transition-colors select-none"
                    >
                        <span>{currentLang.flag}</span>
                        <span className="text-gray-400 text-xs hidden sm:inline">{currentLang.label}</span>
                        <span className="text-gray-500 text-[10px]">▾</span>
                    </button>

                    {langMenuOpen && (
                        <div
                            className="absolute right-0 top-full mt-1 bg-gray-900 border border-gray-700 rounded shadow-xl z-50 min-w-max"
                            onMouseDown={(e) => e.stopPropagation()}
                        >
                            {POKEMON_LANGUAGES.map(lang => (
                                <button
                                    key={lang.code}
                                    type="button"
                                    onClick={() => handleSelectLanguage(lang.code)}
                                    className={`w-full text-left flex items-center gap-2 px-3 py-1.5 text-sm hover:bg-gray-800 transition-colors ${selectedLanguage === lang.code ? 'text-green-400 font-semibold' : 'text-gray-200'}`}
                                >
                                    <span className="w-5 text-center">{lang.flag}</span>
                                    <span>{lang.label}</span>
                                </button>
                            ))}
                        </div>
                    )}
                </div>

                {/* Stats: guessed pokémon / goal */}
                {(() => {
                    const guessedCount = Array.from(checkedIds).filter(id =>
                        id >= 1 && id <= 1025 &&
                        !(id >= STARTER_OFFSET && id < STARTER_OFFSET + 20) &&
                        id < MILESTONE_OFFSET &&
                        !releasedIds.has(id)
                    ).length;
                    const displayGoal = goalCount ?? activePokemonLimit;
                    const isGoalMet = guessedCount >= displayGoal;
                    return (
                        <div className="flex items-center gap-1 text-sm whitespace-nowrap">
                            <span className={`font-bold ${isGoalMet ? 'text-yellow-400' : 'text-green-400'}`}>
                                {guessedCount}
                            </span>
                            <span className="text-gray-500">/</span>
                            <span className="text-gray-300">{displayGoal}</span>
                        </div>
                    );
                })()}

                {/* Feedback toast */}
                {toast && (
                    <div key={toast.id} className={`absolute top-full left-1/2 -translate-x-1/2 mt-2 px-4 py-2 rounded-lg text-sm font-medium shadow-lg transition-all animate-fade-in z-50 whitespace-nowrap ${toast.type === 'success' || toast.type === 'recaught' ? 'bg-green-600 text-white' :
                        toast.type === 'already' ? 'bg-yellow-600 text-white' :
                            toast.type === 'trap' ? 'bg-purple-600 text-white font-bold' :
                                'bg-red-600 text-white'
                        }`}>
                        {toast.message}
                    </div>
                )}

                {/* Debug Hints (dev/beta only) */}
                {(import.meta.env.DEV || __IS_BETA__) && (window as any).isDebugVisible && guess.length >= 2 && (
                    <div className="absolute top-full left-0 right-0 mt-1 bg-gray-900 border border-gray-700 rounded shadow-xl max-h-48 overflow-y-auto z-50">
                        {allPokemon
                            .filter(p => {
                                const clean = getCleanName(p.name).toLowerCase();
                                let isMatch = clean.includes(guess.toLowerCase());

                                if (!isMatch) {
                                    const langNames = pokemonNames[p.id.toString()] ?? {};
                                    isMatch = Object.values(langNames).some(loc => loc.toLowerCase().includes(guess.toLowerCase()));
                                }

                                return isMatch && !checkedIds.has(p.id);
                            })
                            .slice(0, 10)
                            .map(p => (
                                <button
                                    key={p.id}
                                    onClick={() => {
                                        setGuess(displayName(p));
                                        inputRef.current?.focus();
                                    }}
                                    className="w-full text-left px-3 py-1.5 hover:bg-gray-800 text-xs flex justify-between items-center"
                                >
                                    <span>{displayName(p)}</span>
                                    {gameMode === 'standalone' ? (
                                        <span className="text-gray-500 text-[10px] uppercase">Available</span>
                                    ) : isPokemonGuessable(p.id).canGuess ? (
                                        <span className="text-green-500 text-[10px] uppercase font-bold">Unlocked</span>
                                    ) : (
                                        <span className="text-gray-500 text-[10px] uppercase">Locked</span>
                                    )}
                                </button>
                            ))}
                    </div>
                )}
            </div>
        </div>
        <CreditsModal isOpen={isCreditsOpen} onClose={() => setIsCreditsOpen(false)} />
        </>
    );
};
